/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import entidades.*;
import accesoDatos.*;
import controladores.*;
/**
 *
 * @author Usuario
 */
public class GeneralSolBus extends javax.swing.JFrame {

    /**
     * Creates new form GeneralSolBus
     */
    public GeneralSolBus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpEscritorio = new javax.swing.JDesktopPane();
        mbEscritorio = new javax.swing.JMenuBar();
        mPasajes = new javax.swing.JMenu();
        miGestionPasajes = new javax.swing.JMenuItem();
        miHistorialAnular = new javax.swing.JMenuItem();
        mPasajeros = new javax.swing.JMenu();
        mColectivos = new javax.swing.JMenu();
        mHorarios = new javax.swing.JMenu();
        mRutas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        mPasajes.setText("Pasajes");

        miGestionPasajes.setText("Gestion de pasajes");
        miGestionPasajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGestionPasajesActionPerformed(evt);
            }
        });
        mPasajes.add(miGestionPasajes);

        miHistorialAnular.setText("Historial de pasajes y anular ventas");
        mPasajes.add(miHistorialAnular);

        mbEscritorio.add(mPasajes);

        mPasajeros.setText("Pasajeros");
        mbEscritorio.add(mPasajeros);

        mColectivos.setText("Colectivos");
        mbEscritorio.add(mColectivos);

        mHorarios.setText("Horarios");
        mbEscritorio.add(mHorarios);

        mRutas.setText("Rutas");
        mbEscritorio.add(mRutas);

        setJMenuBar(mbEscritorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(dpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(dpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miGestionPasajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGestionPasajesActionPerformed
         Pasaje p = new Pasaje();
        PasajeData pd = new PasajeData();
        vistas.InfGestionPasajes ip =  new vistas.InfGestionPasajes();
         ctrlCargaPasajes cp = new ctrlCargaPasajes(p, pd, ip);
        dpEscritorio.removeAll();
        dpEscritorio.repaint();
        ip.setVisible(true);
        ip.setLocation(00, 00);
        dpEscritorio.add(ip);
        dpEscritorio.moveToFront(ip);
    }//GEN-LAST:event_miGestionPasajesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralSolBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralSolBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralSolBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralSolBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralSolBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpEscritorio;
    private javax.swing.JMenu mColectivos;
    private javax.swing.JMenu mHorarios;
    private javax.swing.JMenu mPasajeros;
    private javax.swing.JMenu mPasajes;
    private javax.swing.JMenu mRutas;
    private javax.swing.JMenuBar mbEscritorio;
    private javax.swing.JMenuItem miGestionPasajes;
    private javax.swing.JMenuItem miHistorialAnular;
    // End of variables declaration//GEN-END:variables
}
