/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import entidades.Horario;
import entidades.Ruta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tDev
 */
public class infGestionRutaHorario extends javax.swing.JInternalFrame {

   private ArrayList<Ruta> rutas = new ArrayList<>();
   private ArrayList<Horario> horarios = new ArrayList<>();
   
    
    
    public infGestionRutaHorario() {
        initComponents();
        
    }
    
    
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRuta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfOrigen = new javax.swing.JTextField();
        jtfDestino = new javax.swing.JTextField();
        jtfDuracion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarRutas = new javax.swing.JTable();
        btnBajaRuta = new javax.swing.JButton();
        btnActRuta = new javax.swing.JButton();
        btnVerTodas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlHorario = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHorarios = new javax.swing.JTable();
        cbRuta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarF = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarHor = new javax.swing.JButton();
        btnBajaHor = new javax.swing.JButton();
        btnActHor = new javax.swing.JButton();

        pnlRuta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlRuta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Origen");
        pnlRuta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setText("Destino");
        pnlRuta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setText("Duracion ");
        pnlRuta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));
        pnlRuta.add(jtfOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 146, -1));
        pnlRuta.add(jtfDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 146, -1));
        pnlRuta.add(jtfDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 146, -1));

        btnAgregar.setText("Agregar");
        pnlRuta.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 110, 30));

        btnFiltrar.setText("Filtrar");
        pnlRuta.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 110, 30));

        tblListarRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListarRutas);

        pnlRuta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 216, 410, 155));

        btnBajaRuta.setText("Eliminar");
        pnlRuta.add(btnBajaRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 100, 40));

        btnActRuta.setText("Actualizar");
        pnlRuta.add(btnActRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 100, 40));

        btnVerTodas.setText("Ver todas");
        pnlRuta.add(btnVerTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 110, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logos/logos32/002-motorway.png"))); // NOI18N
        jLabel4.setText(" RUTAS");
        pnlRuta.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 19, -1, -1));

        pnlHorario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlHorario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tblHorarios);

        pnlHorario.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 163, 320, 209));

        pnlHorario.add(cbRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 233, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logos/logos32/001-bus-schedule.png"))); // NOI18N
        jLabel5.setText(" HORARIOS");
        pnlHorario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        btnAgregarF.setText("Agregar Fila");
        btnAgregarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFActionPerformed(evt);
            }
        });
        pnlHorario.add(btnAgregarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 30));

        jLabel6.setText("Ruta");
        pnlHorario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        btnAgregarHor.setText("Agregar");
        pnlHorario.add(btnAgregarHor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        btnBajaHor.setText("Eliminar");
        pnlHorario.add(btnBajaHor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        btnActHor.setText("Actualizar");
        btnActHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActHorActionPerformed(evt);
            }
        });
        pnlHorario.add(btnActHor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarFActionPerformed

    private void btnActHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActHorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActHorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActHor;
    public javax.swing.JButton btnActRuta;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnAgregarF;
    public javax.swing.JButton btnAgregarHor;
    public javax.swing.JButton btnBajaHor;
    public javax.swing.JButton btnBajaRuta;
    public javax.swing.JButton btnFiltrar;
    public javax.swing.JButton btnVerTodas;
    public javax.swing.JComboBox<Ruta> cbRuta;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jtfDestino;
    public javax.swing.JTextField jtfDuracion;
    public javax.swing.JTextField jtfOrigen;
    public javax.swing.JPanel pnlHorario;
    public javax.swing.JPanel pnlRuta;
    public javax.swing.JTable tblHorarios;
    public javax.swing.JTable tblListarRutas;
    // End of variables declaration//GEN-END:variables
}
