/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import entidades.Ruta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tDev
 */
public class InfListarRutas extends javax.swing.JInternalFrame {
    
    ArrayList<Ruta> rutas = new ArrayList<>();
    private DefaultTableModel model = new DefaultTableModel();

    public InfListarRutas() {
        initComponents();
        armarCabecera();
    }
    
    private void armarCabecera() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Origen");
        filaCabecera.add("Destino");
        filaCabecera.add("Hora de salida");
        filaCabecera.add("Hora de llegada");
        

        for (Object i : filaCabecera) {
            model.addColumn(i);
        }
        tblListarRutas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGrupo = new javax.swing.ButtonGroup();
        spListarRutas = new javax.swing.JScrollPane();
        tblListarRutas = new javax.swing.JTable();
        lblTituloListarRutas = new javax.swing.JLabel();
        rbVerTodasRutas = new javax.swing.JRadioButton();
        rbListarOrigenDestino = new javax.swing.JRadioButton();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();

        tblListarRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spListarRutas.setViewportView(tblListarRutas);

        lblTituloListarRutas.setText("LISTAR RUTAS");

        radioButtonGrupo.add(rbVerTodasRutas);
        rbVerTodasRutas.setText("Ver Todas las Rutas");

        radioButtonGrupo.add(rbListarOrigenDestino);
        rbListarOrigenDestino.setText("Listar por Origen o Destino");

        lblOrigen.setText("Origen");

        lblDestino.setText("Destino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(rbVerTodasRutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDestino)
                                .addComponent(lblOrigen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTituloListarRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDestino)
                    .addComponent(txtOrigen)
                    .addComponent(rbListarOrigenDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(spListarRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloListarRutas)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbVerTodasRutas)
                    .addComponent(rbListarOrigenDestino))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(lblDestino))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrigen)
                            .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(spListarRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblTituloListarRutas;
    private javax.swing.ButtonGroup radioButtonGrupo;
    public javax.swing.JRadioButton rbListarOrigenDestino;
    public javax.swing.JRadioButton rbVerTodasRutas;
    private javax.swing.JScrollPane spListarRutas;
    public javax.swing.JTable tblListarRutas;
    public javax.swing.JTextField txtDestino;
    public javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
